#pragma once

#include <QtGlobal>

#if defined(MAGFEMPROJECTMANAGERPLUGIN_LIBRARY)
#  define MAGFEMPROJECTMANAGERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MAGFEMPROJECTMANAGERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif
